describe('Melakukan Transaksi Pembelian Produk Di Website Demo midtrans', () => {
    it('melakukan Prosess Transaksi Input data dan Checkout', () => {
        cy.visit('https://demo.midtrans.com/')
        cy.url().should('include', 'demo.midtrans.com')
        cy.get('.title').contains('Midtrans Pillow')
        cy.contains('BUY NOW').click()
        cy.get('[data-reactid=".0.0.1.0.2"]').contains('Customer Details')
        cy.wait(500)
        cy.get('[data-reactid=".0.0.1.0.3.0.0.0"]').clear()
        cy.get('[data-reactid=".0.0.1.0.3.0.0.0"]').type('hadidfathan')
        cy.wait(500)
        cy.get('[data-reactid=".0.0.1.0.3.0.0.1"]').clear()
        cy.get('[data-reactid=".0.0.1.0.3.0.0.1"]').type('sieghartmchdol@gmail.com')
        cy.wait(500)
        cy.get('[data-reactid=".0.0.1.0.3.0.0.2"]').clear()
        cy.get('[data-reactid=".0.0.1.0.3.0.0.2"]').type('089831299')
        cy.wait(500)
        cy.get('[data-reactid=".0.0.1.0.3.0.0.3"]').clear()
        cy.get('[data-reactid=".0.0.1.0.3.0.0.3"]').type('Bandung')
        cy.wait(500)
        cy.get('textarea').clear()
        cy.get('textarea').type('Jalan babakan cileunyi')
        cy.wait(500)
        cy.get('[data-reactid=".0.0.1.0.3.0.0.5"]').clear()
        cy.get('[data-reactid=".0.0.1.0.3.0.0.5"]').type('4021')
        cy.wait(500)
        cy.contains('CHECKOUT').click()
        cy.wait(500)
    })

})